In [1]:
import numpy as np

In [2]:
arr = [1,2,3,4,5]

In [3]:
array = np.array(arr)

In [4]:
array


array([1, 2, 3, 4, 5])

In [5]:
mat_arr  = [[1,2,3],[4,5,6],[7,8,9]]
matarr = np.array(mat_arr)

In [7]:
#matarr

In [9]:
np.zeros((2,3
         ))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.63828599, 0.49714385, 0.57483651, 0.66386591, 0.106156  ])

In [13]:
np.random.rand(2,2)

array([[0.03365202, 0.36222153],
       [0.12019787, 0.5280295 ]])

In [15]:
t = np.random.randn(2)

In [16]:
t[1]

0.3003442113675952

In [17]:
t[0]

-1.2836393601179237

In [18]:
np.random.randint(1,100) #100 is not included

3

In [19]:
np.random.randint(1,100,010) #100 is not included

SyntaxError: invalid token (<ipython-input-19-6d6d99b3ef44>, line 1)

In [20]:
np.random.randint(1,100,10) #100 is not included

array([37, 15, 69, 66, 93, 56, 16, 99, 93, 87])

In [23]:
t = np.arange(0,100,5)

In [24]:
t


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [25]:
len(t)

20

In [27]:
t = t.reshape((4,5))

In [28]:
t


array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [29]:
t=t.ravel()

In [30]:
t


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [32]:
t.min()

0

In [33]:
t.max()

95

In [34]:
t.argmax()

19

In [37]:
t.shape

(20,)

In [39]:
t.reshape((4,5)).shape

(4, 5)