In [1]:
import numpy as np

In [2]:
arr  = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [23]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr = np.random.randint(1,100,10)

In [26]:
arr

array([23, 55, 28, 66, 83, 61, 72, 19, 89, 66])

In [28]:
GREATER_THAN_50 = arr[arr>50]

In [29]:
LESSER_THAN_50 = arr[arr<50]

In [30]:
GREATER_THAN_50

array([55, 66, 83, 61, 72, 89, 66])

In [31]:
LESSER_THAN_50

array([23, 28, 19])